services:
  achievements_service.api:
    image: achievements_service.api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "80:8000"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "AchievementsServiceDB"
    ports:
      - "5432:5432"