services:
  achievements_service.api:
    image: achievements_service.api
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - FLASK_APP=api/app.py
    depends_on:
      - db
      - nginx
    networks:
      - default_network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "AchievementsServiceDB"
    ports:
      - "5432:5432"
    networks:
      - default_network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default_network

networks:
  default_network:
